Continue the Translation of PR #103 'Synchronizing with effects (60%)'
reactjs/bn.react.dev pull request #160
Opened 2024-09-28 09:08 UTC by habibium

This PR continues and completes the work started in PR #103 by @AFM-Taha.

- Original PR: #103
- This PR aims to finish the remaining part of the translation

Once reviewed and approved, this PR can replace #103.

2024-10-21 23:06 UTC, habibium commented
@nafistiham @moshfiqrony রিভিউ এর অপেক্ষায়।
আমি শুরু থেকে শেষ পর্যন্ত পড়ে বানানগত, ব্যাকরণগত এবং অনুবাদের অনেক ভুল সংশোধন করেছি।
আপাতত আমার কাছে চলনসই লাগতেছে,  আপনাদের কোনো চেঞ্জের সাজেশন থাকলে জানাবেন।

2024-10-26 06:22 UTC, nafistiham commented on src/content/learn/synchronizing-with-effects.md
> +কিছু কম্পোনেন্টকে বাইরের কোনো সিস্টেমের সাথে সিংক্রোনাইজ করতে হতে পারে। উদাহরণস্বরূপ, আপনি নন-রিয়েক্ট কম্পোনেন্টকে রিয়েক্ট state এর উপর নির্ভর করে নিয়ন্ত্রণ করতে চাইতে পারেন, একটি সার্ভার সংযোগ স্
```suggestion
কিছু কম্পোনেন্টকে বাইরের কোনো সিস্টেমের সাথে সিংক্রোনাইজ করতে হতে পারে। উদাহরণস্বরূপ, আপনি non-React কম্পোনেন্টকে React state এর উপর নির্ভর করে নিয়ন্ত্রণ করতে চাইতে পারেন, একটি সার্ভার সংযোগ স্থাপন করতে, বা যখন একটি কম্পোনেন্ট স্ক্রিনে দেখা যায় তখন একটি analytics লগ পাঠাতে চাইতে পারেন। *Effect* আপনাকে রেন্ডারের পর কিছু কোড রান করার সুযোগ দেয় যাতে আপনি আপনার কম্পোনেন্টটি React এর বাইরে কোন সিস্টেম এর সঙ্গে সিংক্রোনাইজ করতে পারেন।
```

2024-10-26 06:23 UTC, nafistiham commented on src/content/learn/synchronizing-with-effects.md
> +এই পেজে এখানে এবং সামনে, বড় হাতের E যুক্ত "Effect" বা বাংলাতে "ইফেক্ট" উপরের React-specific সংজ্ঞা বোঝায়, অর্থাৎ রেন্ডারিংয়ের ফলে সৃষ্ট side effect। বিস্তৃত এই প্রোগ্রামিং concept টি বুঝাতে, আমরা এটি
বাংলাতে ইফেক্ট অংশটুকু যোগ করার দরকার নেই।

2024-10-26 06:24 UTC, nafistiham commented on src/content/learn/synchronizing-with-effects.md
> +    // *প্রতিবার* রেন্ডারে এখানের code রান হবে
কোডের মধ্যকার লেখা অনুবাদ না করি।

2024-10-26 06:24 UTC, nafistiham commented on src/content/learn/synchronizing-with-effects.md
> +উপরন্তু, যখন `VideoPlayer` কে প্রথমবারের জন্য call করা হয়, এটির DOM তখন exist করে না! `play()` বা `pause()` করার জন্য এখানে কোন DOM node নাই, কারণ React জানে না কি DOM তৈরি হবে যতক্ষণ না আপনি JSX রিট
```suggestion
উপরন্তু, যখন `VideoPlayer` কে প্রথমবারের জন্য call করা হয়, এটির DOM তখন exist করে না! `play()` বা `pause()` করার জন্য এখানে কোন DOM node নাই, কারণ React জানে না কী DOM তৈরি হবে যতক্ষণ না আপনি JSX রিটার্ন করেন। 
```

2024-10-26 06:29 UTC, nafistiham requested changes
অনেক ধন্যবাদ বিশাল একটা পেইজে কাজ করবার জন্য।
কিছু কমেন্ট করেছি। কিছু বিষয় পরিবর্তনের অনুরোধ করব। 

1. কমিটের সংখ্যা অত্যধিক এবং অপ্রয়োজনীয় মনে হয়েছে। একটা দুইটা শব্দ বদলিয়ে কমিট করা হয়েছে। অনুরোধ করব কমিটগুলোকে স্কোয়াশ করে ২০-৩০ টা কমিটে নিয়ে যেতে। 
2. React সহ অনেক টেকনিকাল শব্দ আমরা ইংরেজিতেই রাখার চেষ্টা করছি। এ বিষয়ে আরেকবার রিভাইজ করলে ভাল হয়।
3. কোডের মধ্যকার কিছু না বদলাই। সি আই সি ডি পাইপলাইনে ঝামেলা করে মাঝে মাঝে। 

এ বিষয়গুলো মাথায় রেখে আরেকবার ঠিক করেন। এর পর আবার রিভিউ করব।

2024-10-26 06:31 UTC, habibium commented on src/content/learn/synchronizing-with-effects.md
> +    // *প্রতিবার* রেন্ডারে এখানের code রান হবে
alright

2024-10-26 08:51 UTC, habibium commented
> অনেক ধন্যবাদ বিশাল একটা পেইজে কাজ করবার জন্য। কিছু কমেন্ট করেছি। কিছু বিষয় পরিবর্তনের অনুরোধ করব।
> 
> 1. কমিটের সংখ্যা অত্যধিক এবং অপ্রয়োজনীয় মনে হয়েছে। একটা দুইটা শব্দ বদলিয়ে কমিট করা হয়েছে। অনুরোধ করব কমিটগুলোকে স্কোয়াশ করে ২০-৩০ টা কমিটে নিয়ে যেতে।
> 2. React সহ অনেক টেকনিকাল শব্দ আমরা ইংরেজিতেই রাখার চেষ্টা করছি। এ বিষয়ে আরেকবার রিভাইজ করলে ভাল হয়।
> 3. কোডের মধ্যকার কিছু না বদলাই। সি আই সি ডি পাইপলাইনে ঝামেলা করে মাঝে মাঝে।
> 
> এ বিষয়গুলো মাথায় রেখে আরেকবার ঠিক করেন। এর পর আবার রিভিউ করব।

@nafistiham রিভিউর জন্য ধন্যবাদ।

1. প্রায় এক সপ্তাহ ধরে কাজের ফাঁকে ফাঁকে প্রুফ রীড করে সংশোধন করায় এত এত ভাঙ্গা কমিট হয়েছে শেষের দিকে, সেগুলো সব (প্রায় ৫৩ টা) আমি squash করে ১ টি কমিট করেছি। বর্তমান কমিটগুলোর মধ্যে ২/৩ টা বাদে বাকিগুলোতে ১ টি  করে প্যারাগ্রাফ অনুবাদ করা হয়েছে, আর এত বড় একটা পেজের জন্য এত সংখ্যক কমিট স্বাভাবিক মনে করি। তবুও আরো এডজাস্ট করতে হলে জানাবেন।
2. পুরো পেজ রিভাইজ দিয়ে প্রায় সব টেকনিকাল টার্মগুলোকে ইংরেজিতে ফিরিয়ে নিয়েছি।
3. কোডব্লক সব আগের মতো করে দিয়েছি।

2025-06-29 05:35 UTC, moshfiqrony approved these changes
LGTM

2025-06-29 05:35 UTC, merged