WIP - Start a new project page
reactjs/bn.react.dev pull request #2
Opened 2023-04-29 14:44 UTC by moshfiqrony

2023-04-29 18:46 UTC, nafistiham requested changes
Not all are change requests. Some are general feedback.

2023-04-29 18:46 UTC, nafistiham commented on src/content/learn/start-a-new-react-project.md
> +আপনি যদি React দিয়ে কোন অ্যাপ বা ওয়েবসাইট বানাতে চান তাহলে, React কমিউনিটি ব্যাবহার করে এমন যেকোনো একটি জনপ্রিয় ফ্রেমওয়ার্ক ব্যাবহার করতে আমরা আপনাকে উৎসাহিত করব। এই ফ্রেমওয়ার্ক গুল আপনাকে গুরুত্বপূর
ফ্রেমওয়ার্ক গুল আপনাকে  -> ফ্রেমওয়ার্ক গুলো আপনাকে
সব ধরনের অ্যাপ -> সব ধরণের অ্যাপ

2023-04-29 18:46 UTC, nafistiham commented on src/content/learn/start-a-new-react-project.md
> +## জনপ্রিয় React ফ্রেমওয়ার্ক গুলো {/*production-grade-react-frameworks*/}
আমার মনে হয়, জনপ্রিয় এর জায়গায় "ইন্ডাস্ট্রিতে ব্যবহার করা যায় এমন" ধরণের কোন শব্দ দিলে বা Production-grade রেখে দেওয়া যেতে পারে। 
আর বাক্যটা 
কিছু জনপ্রিয় React ফ্রেমওয়ার্কের তালিকা, বা
কিছু জনপ্রিয় React ফ্রেমওয়ার্ক 
এমন দিলে আরো পাঠযোগ্য হবে।

জরুরী না। suggestion

2023-04-29 18:46 UTC, nafistiham commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) একটি full-stack React ফ্রেমওয়ার্ক.** এটি খুবই জনপ্রিয় এবং খুবই সহজে একটি ছোট ব্লগ ওয়েবসাইট অথবা অনেক বড় এবং জটিল অ্যাপ বানানোর জন্যে উপযোগী। নিচের কম্যান্ড টি আপনার ট
কম্যান্ড -> কমান্ড

2023-04-29 20:23 UTC, shakib609 commented on src/content/learn/start-a-new-react-project.md
> +[Vercel](https://vercel.com/) Next.js এর রক্ষণাবেক্ষণের কাজ করে থাকে। যেকোনো Node.js অথবা serverless হোস্টিং, অথবা আপনার নিজস্ব সার্ভারে [একটি Next.js অ্যাপ deploy](https://nextjs.org/docs/deployment
```suggestion
[Vercel](https://vercel.com/) Next.js এর রক্ষণাবেক্ষণের কাজ করে থাকে। যেকোনো Node.js অথবা serverless হোস্টিং, অথবা আপনার নিজস্ব সার্ভারে [একটি Next.js অ্যাপ deploy](https://nextjs.org/docs/deployment) করতে পারবেন। [সম্পূর্ণ স্ট্যাটিক Next.js অ্যাপ](https://nextjs.org/docs/advanced-features/static-html-export) যেকোনো স্ট্যাটিক হোস্টিং এ deploy করা যায়।
```

2023-04-29 20:24 UTC, shakib609 requested changes

2023-04-29 20:24 UTC, shakib609 commented on src/content/learn/start-a-new-react-project.md
> +[Vercel](https://vercel.com/) Next.js এর রক্ষণাবেক্ষণের কাজ করে থাকে। যেকোনো Node.js অথবা serverless হোস্টিং, অথবা আপনার নিজস্ব সার্ভারে [একটি Next.js অ্যাপ deploy](https://nextjs.org/docs/deployment
```suggestion
[Vercel](https://vercel.com/) Next.js এর রক্ষণাবেক্ষণের কাজ করে থাকে। যেকোনো Node.js অথবা serverless হোস্টিং, অথবা আপনার নিজস্ব সার্ভারে [একটি Next.js অ্যাপ deploy](https://nextjs.org/docs/deployment) করতে পারবেন। [সম্পূর্ণ স্ট্যাটিক Next.js অ্যাপ](https://nextjs.org/docs/advanced-features/static-html-export) যেকোনো স্ট্যাটিক হোস্টিং এ deploy করা যায়।
```

2023-04-30 09:31 UTC, moshfiqrony commented
Closing this PR because of the fork procedure not followed.

2023-04-30 09:31 UTC, closed without merging