Reference/react/suspense
reactjs/bn.react.dev pull request #33
Opened 2023-05-19 18:44 UTC by nz-m

2023-05-20 16:19 UTC, nafistiham commented on src/content/reference/react/Suspense.md
> +
927 is an extra line. Needs removal.
```suggestion
```

2023-05-20 16:20 UTC, nafistiham commented on src/content/reference/react/Suspense.md
> +[`useDeferredValue`](/reference/react/useDeferredValue) হুকটি আপনাকে query করার একটি deferred ভার্সন পাঠানোর সুবিধা দেয়ঃ
merge 1121 and 1122

2023-05-20 16:24 UTC, nafistiham commented
@nz-m vai, please check the number of lines added and subtracted. We are trying to keep the paragraphs aligned. I have showed 2 lines as example. There must have been more. Because you deleted 69 lines and added 81 lines. So, please check the differences and merge accordingly. Is your PR finished? We are keeping the PR as a draft as long as we are adding commits. So, if you are finished, make it ready for review and put a comment here that you are done. We won't review until then. 

This is a huge page. Thanks for doing it.

2023-05-20 16:37 UTC, nz-m commented
@nafistiham ২/১ টা এক্সট্রা লাইন ভুলে চলে আসছে। এগুলা ঠিক করে আরেকটা PR দিচ্ছি। আর কিছু sentence বাংলা করতে লাইন কিছুটা হয়ত বেড়ে গিয়েছে। এটার জন্য কি কোনো সমস্যা হবে?

2023-05-20 17:09 UTC, nafistiham commented
আপনি আগের মার্জ হওয়া PR একটু চোখ বুলাতে পারেন। আমি যতদূর দেখেছি, সবগুলাতেই এক্সাক্ট লাইনে অনুবাদ করা গেছে। 
PR দিলে আমরা একবারে রিভিউ করে দিব। তখন হয়ত বুঝব।

2023-05-20 17:40 UTC, nz-m commented
@nafistiham I'm done with PR.

2023-05-20 19:08 UTC, nafistiham requested changes
অনুবাদ সব দিক দিয়ে বেশ ভাল হয়েছে। বাংলা ইংরেজি করার দিকে কিছুটা অসংগতি দেখছি। তবে সেটাও তেমন সমস্যা না। যেগুলো রিভিউ দিলাম সবগুলাই করতে হবে এমন না। সাজেশনও রয়েছে।

আরো কিছু সাজেশন যা এখানে লিখি নাই। অনেক তৎসম শব্দ আমরা ব্যবহার না করলে আরো পাঠযোগ্য হবে। এবং এই পেইজেই সেরকম কিছু একেকবার একেকরকম উদাহরণ আছে।
যেমন, আপডেট অনেক জায়গাতেই আপডেটা আবার অনেক জায়গায় হালনাগাদ। এইটা সব কিছু আপডেট করে দিতে পারেন।
প্রদর্শন, সর্বদা এরকম পুরোনো ধরণের শব্দের জায়গায় ক্ষেত্রবিশেষে দেখানো, সবসময় এমন শব্দ ব্যবহার করা যেতে পারে।

মোট কথা আমরা নিজেরা চলতি ভাষায় কাউকে কিছু বুঝাতে গেলে যে শব্দগুলা দিয়ে প্রতিস্থাপন করে নিতাম সেগুলোই ভদ্রস্থ ভাবে এখানে লিখতে পারি। যেকোন পরিবর্তনে আপনার দ্বিমত থাকতে পারে। নিঃসংকোচে শেয়ার করবেন। 

@nomandhoni-cs ভাই, এই পেইজটা দেখবেন সময় পেলে।

নিয়াজ ভাই আবারো ধন্যবাদ। বেশ বড় পেইজ।

2023-05-20 19:08 UTC, nafistiham commented on src/content/reference/react/Suspense.md
> +উপরের উদাহরনটিতে, আপনি যদি একবার বাটনটিতে ক্লিক করেন দেখবেন কোনো দৃশ্যমান ইন্ডিকেশন নেই যে একটি নেভিগেশনের অগ্রগতি হচ্ছে। একটি ইন্ডিকেটর যোগ করতে আপনি [`startTransition`](/reference/react/startTransi
```suggestion
উপরের উদাহরণটিতে, আপনি যদি একবার বাটনটিতে ক্লিক করেন দেখবেন কোনো দৃশ্যমান ইংগিত নেই যে একটি নেভিগেশনের অগ্রগতি হচ্ছে। একটি ইন্ডিকেটর যোগ করতে আপনি [`startTransition`](/reference/react/startTransition) এর স্থানে [`useTransition`](/reference/react/useTransition) ব্যবহার করতে পারেন যা আপনাকে একটি boolean মান `isPending` দেয়। নিচের উদাহরণে ওয়েবসাইটের হেডার স্টাইল পরিবর্তন করার সময় একটি ট্রান্সিশন ঘটছে তা দেখানোর জন্য এটি ব্যবহার করা হয়েছেঃ
```

2023-05-20 19:08 UTC, nafistiham commented on src/content/reference/react/Suspense.md
> +React ক্লায়েন্টে একই আবার কম্পোনেন্টটি রেন্ডার করার চেষ্টা করবে। যদি ক্লায়েন্টেও এরর হয়, React এররটি থ্রো করবে এবং নিকটতম [error boundary](/reference/react/Component#static-getderivedstatefromerror)
```suggestion
ক্লায়েন্টে, একই কম্পোনেন্টটি Reactআবার রেন্ডার করার চেষ্টা করবে। যদি ক্লায়েন্টেও এরর হয়, React এররটি থ্রো করবে এবং নিকটতম [error boundary](/reference/react/Component#static-getderivedstatefromerror) টি প্রদর্শন করবে। তবে, যদি ক্লায়েন্টে এরর না হয়, React এরর টি ক্লায়েন্টে দেখাবে না যেহেতু কন্টেন্টটি শেষ পর্যন্ত সফলভাবে প্রদর্শিত হয়েছিল।
```

2023-05-20 20:51 UTC, nz-m commented
@nafistiham updated according to your suggestions.

2023-05-21 03:57 UTC, nafistiham approved these changes
Nice work! LGTM.

2023-05-21 03:58 UTC, merged