Manipulating the dom with refs
reactjs/bn.react.dev pull request #34
Opened 2023-05-21 15:32 UTC by nafistiham

2023-05-23 11:44 UTC, nomandhoni-cs commented
@moshfiqrony ভাই আপনি Fork কে কিভাবে উচ্চারণ করেন? আমি ফোর্ক উচ্চারণ করি আমি বুঝতেছি না কোনটা সঠিক।

2023-05-23 11:56 UTC, nomandhoni-cs commented
@nafistiham ভাই, আপনার ইংরেজি শব্দগুলো আমার কাছে মোটামুটি ঠিকই মনে হয়েছে।

Reset = পুনরায় শুরু করুন

ব্যবহার করা যেতে পারে যেহেতু এখানে যে ডকুমেন্টেশন পড়ছে তাকে আমরা নির্দেশ করতেছি।

@moshfiqrony ভাই, আপনি Fork কে কিভাবে উচ্চারণ করেন? আমি ফোর্ক উচ্চারণ করি আমি বুঝতেছি না কোনটা সঠিক।

2023-05-23 12:01 UTC, nafistiham commented
রিসেট আসলে রিসেটই রাখা লাগবে। একটা বাটন তো। আমি রিসেট করুন, ডাউনলোড করুন এমন দিছিলাম। কিন্তু বাজে দেখায়। 

আর ইংরেজী শব্দে সংবৃত উচ্চারণ বিবৃত উচ্চারণ আসলেই একটা ঝামেলা। ফর্ক ফোর্ক কোনোটাতেই আমার সমস্যা নাই।

2023-05-23 13:02 UTC, nomandhoni-cs commented
Okay bhai tahole রিসেট ই  রাখেন

2023-05-23 13:04 UTC, nomandhoni-cs commented
> রিসেট আসলে রিসেটই রাখা লাগবে। একটা বাটন তো। আমি রিসেট করুন, ডাউনলোড করুন এমন দিছিলাম। কিন্তু বাজে দেখায়। 
> 
> আর ইংরেজী শব্দে সংবৃত উচ্চারণ বিবৃত উচ্চারণ আসলেই একটা ঝামেলা। ফর্ক ফোর্ক কোনোটাতেই আমার সমস্যা নাই।

আমি প্রবলেম বলি নাই আমি আসলে জানতে চাচ্ছিলাম যে আমার উচ্চারণটা সঠিক কিনা ।

2023-05-23 13:19 UTC, nafistiham commented
> > রিসেট আসলে রিসেটই রাখা লাগবে। একটা বাটন তো। আমি রিসেট করুন, ডাউনলোড করুন এমন দিছিলাম। কিন্তু বাজে দেখায়। 
> > 
> > আর ইংরেজী শব্দে সংবৃত উচ্চারণ বিবৃত উচ্চারণ আসলেই একটা ঝামেলা। ফর্ক ফোর্ক কোনোটাতেই আমার সমস্যা নাই।
> 
> আমি প্রবলেম বলি নাই আমি আসলে জানতে চাচ্ছিলাম যে আমার উচ্চারণটা সঠিক কিনা ।

হ্যা আমিও তাই বললাম যে আমার হিসেবে দুইটাই চলে। দ্বিমত নাই।

2023-05-23 13:28 UTC, nomandhoni-cs requested changes

2023-05-23 13:28 UTC, nomandhoni-cs commented on src/content/learn/manipulating-the-dom-with-refs.md
> +এটি ঘটে কারণ স্বাভাবিকভাবে React কম্পোনেন্টকে অন্যান্য কম্পোনেন্টের DOM নোড অ্যাক্সেস করতে দেয় না। তার নিজের childrenদের জন্যও নয়! এটি ইচ্ছাকৃত। Ref এক ধরণের escape hatch যা খুব কম ব্যবহার করা উচিত
```suggestion
এটি ঘটে কারণ স্বাভাবিকভাবে React কম্পোনেন্টকে অন্যান্য কম্পোনেন্টের DOM নোড অ্যাক্সেস করতে দেয় না। তার নিজের children দের জন্যও নয়! এটি ইচ্ছাকৃত। Ref এক ধরণের escape hatch যা খুব কম ব্যবহার করা উচিত। ম্যানুয়ালি _অন্য_ কম্পোনেন্টের DOM নোড পরিবর্তন করা আপনার কোডকে আরও নাজুক বানিয়ে ফেলে।
```

2023-05-23 13:28 UTC, nomandhoni-cs commented on src/content/learn/manipulating-the-dom-with-refs.md
> +এই উদাহরণে, ভিডিও চালু এবং বন্ধ থাকা অবস্থার সুইচ করার জন্য বাটন একটি state ভ্যারিয়েবল পরিবর্তন করে। তবে, ভিডিও আসলেই বন্ধ বা চালু করার জন্য, state ভ্যারিয়েবল পরিবর্তন করা যতেষ্ট না। আপনাকে `<video>`
```suggestion
এই উদাহরণে, ভিডিও চালু এবং বন্ধ থাকা অবস্থার সুইচ করার জন্য বাটন একটি state ভ্যারিয়েবল পরিবর্তন করে। তবে, ভিডিও আসলেই বন্ধ বা চালু করার জন্য, state ভ্যারিয়েবল পরিবর্তন করা যথেষ্ট না। আপনাকে `<video>` এর DOM এলিমেন্টে [`play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) এবং [`pause()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause) কল করতে হবে। এর সাথে একটি ref যোগ করুন, এবং নিশ্চিত করুন যে বাটনটা কাজ করছে।
```

2023-05-23 13:42 UTC, nomandhoni-cs approved these changes

2023-05-23 13:43 UTC, merged

2023-05-24 03:31 UTC, moshfiqrony commented
Sorry for not being able to reply :(

2023-05-24 03:32 UTC, nafistiham commented
No problem vai. We all have our lives.