Translate: API Reference > Hook > useCallback till reference
reactjs/bn.react.dev pull request #35
Opened 2023-05-21 19:37 UTC by asif-jalil

Translating useContext in one PR is difficult. That's why I work on intro and reference to make this pull request. Rest will be done with other PRs.

![usecallback](https://github.com/reactjs/bn.react.dev/assets/62372647/117a28f1-2a9d-412f-aed1-ab84d7fc8e5e)

2023-05-21 21:16 UTC, nz-m commented on src/content/reference/react/useContext.md
> +`useContext` হচ্ছে একটি React হুক যেটা আপনাকে কম্পোনেন্ট থেকে [context](/learn/passing-data-deeply-with-context) পড়তে এবং সাবস্কাইব করতে দিবে।
A line is shifted here. It should have started from line 7.

2023-05-22 04:54 UTC, nafistiham requested changes
React থেকে কিছু পরিবর্তন আসছে আমাদের এখানে। যে কারণে লিন্টার কাজ করবে না বোধ হয়। মেইন থেকে পুল নিয়ে এনভায়রনমেন্টটা আরেকবার আপডেট করে পুশ করতে হবে।

2023-05-22 04:54 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +[নীচে আরো উদাহরণ দেখুন.](#usage)
```suggestion
[নীচে আরো উদাহরণ দেখুন।](#usage)
```

2023-05-22 04:54 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +[context](/learn/passing-data-deeply-with-context) পড়া এবং সেখানে সাবস্ক্রাইব করার জন্য `useContext` কে আপনার কম্পোনেন্ট এর একেবারে উপরের স্তরে কল করতে হবে।
```suggestion
[context](/learn/passing-data-deeply-with-context) রিড করা এবং সেখানে সাবস্ক্রাইব করার জন্য `useContext` কে আপনার কম্পোনেন্ট এর একেবারে উপরের স্তরে কল করতে হবে।
```
টেকনিকাল সেন্সে রিড এবং রাইটকে আসলে পড়া এবং লেখা বলা যায় না। এইজন্য আমরা রিড করা বা read করা ব্যবহার করছি, যতটা পারা যায়।

2023-05-22 04:54 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +* `SomeContext`: এটি হচ্ছে সেই context যেটি আপনি পূর্বে [`createContext`](/reference/react/createContext) দ্বারা তৈরি করেছিলেন। context নিজে থেকে তথ্য ধারণ করে না, এটি শুধুমাত্র সেই তথ্যগুলিকেই উপস্থ
```suggestion
* `SomeContext`: এটি হচ্ছে সেই context যেটি আপনি আগে [`createContext`](/reference/react/createContext) ব্যবহার করে তৈরি করেছিলেন। context নিজে থেকে তথ্য ধারণ করে না, এটি শুধুমাত্র সেই তথ্যগুলিকেই উপস্থাপন করে যা আপনি দিতে পারেন অথবা কম্পোনেন্ট থেকে রিড করতে পারেন।
```

আমরা চেষ্টা করছি লেখাগুলো পাঠযোগ্য করার জন্য যেসব জায়গায় সম্ভব তৎসম শব্দ ব্যবহার না করে চলিত শব্দ ব্যবহার করার।

2023-05-22 04:54 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +যে কম্পোনেন্টে `useContext` কল করা হয় তার জন্য context এর ভ্যালু রিটার্ন করে। যে কম্পোনেন্ট কল করা হয়েছে তার উপরে কম্পোনেন্ট ট্রির সব থেকে কাছের `SomeContext.Provider` দ্বারা নির্ধারিত হয় যা `value`
```suggestion
যে কম্পোনেন্টে `useContext` কল করা হয় তার জন্য context এর ভ্যালু রিটার্ন করে। যে কম্পোনেন্ট কল করা হয়েছে তার উপরে কম্পোনেন্ট ট্রির সব থেকে কাছের `SomeContext.Provider` দ্বারা নির্ধারিত হয় যা `value` হিসাবে পাঠানো হয়। যদি এমন কোন provider না থাকে, তাহলে তার রিটার্ন করা মান হবে `defaultValue`  যা আপনি context এর জন্য [`createContext`](/reference/react/createContext) এ পাঠিয়েছিলেন। রিটার্ন্ড মান সবসময় আপ টু ডেট হবে। যদি context এ কোন পরিবর্তন হয়, তাহলে context ব্যবহারকৃত কম্পোনেন্টগুলোকে React স্বয়ংক্রিয়ভাবে পুনরায় রেন্ডার করবে।
```

ইংরেজি সবদ্যার বাংলা উচ্চারণের সাথে তৎসম প্রত্যয় যথাসম্ভব না ব্যবহার করাই ভাল। এখানে লেখা একটু বড় করে বুঝিয়ে দেওয়া যেতে পারে না সরাসরি ওই শব্দও ব্যবহার করা যেতে পারে যেমন returned / রিটার্ন্ড / রিটার্নড

2023-05-22 04:54 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +* একটি কম্পোনেন্টের ভিতর `useContext()` কল করা হলে সেই *একই* কম্পোনেন্ট থেকে রিটার্নকৃত প্রদানকারীদের দ্বারা এটি প্রভাবিত হবে না। যে কম্পোনেন্ট থেকে `useContext()` কল করা হয়েছে, সংশ্লিষ্ট `<Context.P
```suggestion
* একটি কম্পোনেন্টের ভিতর `useContext()` কল করা হলে সেই *একই* কম্পোনেন্ট থেকে রিটার্নড হওয়া providers দিয়ে এটি প্রভাবিত হবে না। যে কম্পোনেন্ট থেকে `useContext()` কল করা হয়েছে, সংশ্লিষ্ট `<Context.Provider>` কে সেই কম্পোনেন্টের ***উপরে* থাকতে হবে**
```

আমার মনে হচ্ছে পুরো পেইজেই provider কে একই রাখা উচিত। provider বা প্রোভাইডার। প্রদানকারী কথাটা আমার মনে হয় টেকনিকালভাবে সঠিক হচ্ছে না। আপনার দ্বিমত থাকলে অবশ্যই জানাতে পারেন।

2023-05-23 05:54 UTC, nafistiham approved these changes
LGTM

2023-05-23 05:56 UTC, merged

2023-05-29 19:15 UTC, asif-jalil commented
This pull request needs to mention in this #1 issue @nafistiham

2023-05-30 02:18 UTC, nafistiham commented
> This pull request needs to mention in this #1 issue @nafistiham

Done. Please change the PR names as requested in the other PR. Thanks.