Translate: API Reference > Hook > useCallback usages section
reactjs/bn.react.dev pull request #37
Opened 2023-05-22 19:30 UTC by asif-jalil

2023-05-23 06:02 UTC, nafistiham commented
Thanks a lot Asif vai for making quick translations. I would like to request you to not open more than one PR at a time as mentioned in our [guidelines](https://github.com/reactjs/bn.react.dev/issues/32). It will help us keep our PR list simple. So, let's open another PR after the previous one is merged and closed. Larger PRs are difficult to review. SImilarly, too many PRs mean too many back and forths. We are trying to find a sweet spot. I think, we can easily accommodate 60/80 line changes in one PR, meaning 40 additions and 40 deletions. Thanks again for your contribution.

2023-05-27 03:49 UTC, moshfiqrony commented
@asif-jalil bhai assuming you got what @nafistiham bhai explained.

2023-05-27 05:56 UTC, asif-jalil commented
Yeah got it.

2023-05-30 02:14 UTC, nafistiham requested changes
বেশ গোছানো ভাষান্তর হয়েছে। অনেক ধন্যবাদ। কিছু টাইপো রিকুয়েস্ট করেছি। আর আমরা নন টেকনিকাল শব্ধগুলো একটু বামে ডানে গিয়ে বাংলা করে ফেলতে পারি। সেগুলো ইংরেজি হরফে বা ইংরেজি উচ্চারণে রাখা জরুরি না। ৬৫ নাম্বার লাইনে অমিল ছিল। আবার নিচে একটা লাইন অতিরিক্ত ইংরেজি আছে। দুইটা ঠিক করলে সম্পূর্ণ মিলে যাবে। 

যেহেতু দুটি PR এ দিয়েছেন, আমাদের ইস্যুর পরিচ্ছন্নতার জন্য অনুরোধ থাকবে PR দুইটার নাম সহজ করে useContext part 1, useContext part 2 বা সেরকম কিছু করে দেবেন। আবারও ধন্যবাদ।

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +এই উদাহরণে, `MyApp` কম্পোনেন্ট একটি state ভ্যারিয়েবল ধারণ করে যা পরবর্তিতে `ThemeContext` provider এ পাস করা হয়। "Dark mode" চেকবক্স চেক করলে state আপডেট হয়। প্রদত্ত মানের পরিবর্তন সেই সব কম্পোনেন্ট
```suggestion
এই উদাহরণে, `MyApp` কম্পোনেন্ট একটি state ভ্যারিয়েবল ধারণ করে যা পরবর্তীতে `ThemeContext` provider এ পাস করা হয়। "Dark mode" চেকবক্স চেক করলে state আপডেট হয়। প্রদত্ত মানের পরিবর্তন সেই সব কম্পোনেন্টকে পুনরায় রেন্ডার করে যারা এই context ব্যবহার করেছে।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +আপনার অ্যাপ গ্রো করার সাথে সাথে আপনার অ্যাপের রুটের কাছাকাছি context গুলোর একটি "পিরামিড" থাকবে বলে আশা করা যাচ্ছে। এটাতে কোন সমস্যা নেই। যাইহোক, আপনি যদি নান্দনিকভাবে নেস্টিং অপছন্দ করেন, তাহলে আপনি
```suggestion
আপনার অ্যাপ বড় হবার সাথে সাথে আপনার অ্যাপের রুটের কাছাকাছি context গুলোর একটি "পিরামিড" থাকবে বলে আশা করা যাচ্ছে। এটাতে কোন সমস্যা নেই। যাই হোক, আপনি যদি নান্দনিকভাবে নেস্টিং অপছন্দ করেন, তাহলে আপনি একটি কম্পোনেন্টে provider গুলোকে পৃথক করে ফেলতে পারেন। এই উদাহরণে, `MyProviders` "plumbing" লুকিয়ে রাখে এবং এর ভিতর দিয়ে প্রয়োজনীয় provider দের জন্য পাস করা চিলড্রেন রেন্ডার করে। উল্লেখ্য যে `MyApp` এ `theme` এবং `setTheme` state প্রয়োজন, তাই `MyApp` এখনও state এর এই অংশটুকুর মালিক।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +এই উদাহরণের [সম্পূর্ন ওয়াকথ্রু](/learn/scaling-up-with-reducer-and-context) পড়ুন।
```suggestion
এই উদাহরণের [সম্পূর্ণ ওয়াকথ্রু](/learn/scaling-up-with-reducer-and-context) পড়ুন।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +### ফলব্যাক এর ক্ষেত্রে ডিফল্ট মান নির্ধারন করা {/*specifying-a-fallback-default-value*/}
```suggestion
### ফলব্যাক এর ক্ষেত্রে ডিফল্ট মান নির্ধারণ করা {/*specifying-a-fallback-default-value*/}
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
>  If React can't find any providers of that particular <CodeStep step={1}>context</CodeStep> in the parent tree, the context value returned by `useContext()` will be equal to the <CodeStep step={3}>def
ইংরেজি বাক্য রয়ে গেছে।

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +React যদি প্যারেন্ট ট্রিতে নির্দিষ্ট <CodeStep step={1}>context</CodeStep> এর কোন provider খুঁজে না পায়, তাহলে `useContext()` থেকে রিটার্ন্ড context এর মান ডিফল্ট মানের সমান হবে যা আপনি সেই [context
```suggestion
React যদি প্যারেন্ট ট্রিতে নির্দিষ্ট <CodeStep step={1}>context</CodeStep> এর কোন provider খুঁজে না পায়, তাহলে `useContext()` থেকে রিটার্ন্ড context এর মান ডিফল্ট মানের সমান হবে যা আপনি সেই [context টি তৈরি](/reference/react/createContext) করার সময় নির্ধারণ করেছিলেনঃ
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +এইভাবে, আপনি যদি দুর্ঘটনাক্রমে সংশ্লিষ্ট provider ছাড়া কোন কম্পোনেন্ট রেন্ডার করেন, তবে এটি ব্রেক করবে না। এটি আপনার কম্পোনেন্টগুলিকে টেস্টের সময় অনেক অনেক provider সেট আপ না করে একটি টেস্ট ইনভায়রনম
```suggestion
এইভাবে, আপনি যদি দুর্ঘটনাক্রমে সংশ্লিষ্ট provider ছাড়া কোন কম্পোনেন্ট রেন্ডার করেন, তবে এটি ভাংবে না। এটি আপনার কম্পোনেন্টগুলিকে টেস্টের সময় অনেক অনেক provider সেট আপ না করে একটি টেস্ট ইনভায়রনমেন্টে ভালভাবে কাজ করতে সহায়তা করে।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +আপনি ট্রির একটি অংশকে একটি ভিন্ন মান সহ একটি provider দিয়ে র‍্যাপ করার মাধ্যমে সেই অংশের জন্য context টি ওভাররাইড করতে পারেন।
```suggestion
আপনি ট্রির একটি অংশকে একটি ভিন্ন মান সহ একটি provider দিয়ে wrap করার মাধ্যমে সেই অংশের জন্য context টি ওভাররাইড করতে পারেন।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +এই উদাহরণের [সম্পূর্ন ওয়াকথ্রু](/learn/passing-data-deeply-with-context) পড়ুন।
```suggestion
এই উদাহরণের [বিস্তারিত ওয়াকথ্রু](/learn/passing-data-deeply-with-context) পড়ুন।
```

2023-05-30 02:14 UTC, nafistiham commented on src/content/reference/react/useContext.md
> +ছোট অ্যাপগুলিতে এটি কোনো সমস্যা নয়। যাইহোক, যদি `currentUser` এর মত অন্তর্নিহিত ডেটা পরিবর্তিত না হয় তবে তাদের পুনরায় রেন্ডার করার কোন প্রয়োজন নেই। এই ক্ষেত্রে React কে সুবিধা নিতে সাহায্য করার জ
```suggestion
ছোট অ্যাপগুলিতে এটি কোনো সমস্যা নয়। যাই হোক, যদি `currentUser` এর মত অন্তর্নিহিত ডেটা পরিবর্তিত না হয় তবে তাদের পুনরায় রেন্ডার করার কোন প্রয়োজন নেই। এই ক্ষেত্রে React কে সুবিধা নিতে সাহায্য করার জন্য আপনি [`useCallback`](/reference/react/useCallback) দিয়ে `login` ফাংশনটি wrap করে দিতে পারেন এবং object তৈরিকে [`useMemo`](/reference/react/useMemo) দিয়ে wrap করে দিতে পারেন। এটি একটি পারফরমেন্স অপ্টিমাইজেশানঃ
```

2023-05-31 04:35 UTC, nafistiham approved these changes
Great work Asif bhai! LGTM!

2023-05-31 04:36 UTC, merged