Translate: Reference > Hooks
reactjs/bn.react.dev pull request #39
Opened 2023-05-23 20:15 UTC by SusmoySenGupta

2023-05-24 03:04 UTC, nafistiham commented
অনেক ধন্যবাদ অনুবাদে কন্ট্রিবিউট করার জন্য। কিছু বিষয় আমরা একইরকম রাখার চেষ্টা করছি।

- লাইন নাম্বার একই রাখা। অর্থাৎ যে লাইনে ইংরেজি রয়েছে সেই লাইনেই বাংলা করা। এতে সামঞ্জস্য ঠিক থাকবে।
- কিছু টেকনিকাল বিষয় যেগুলা একই সাথে ইংরেজিতেও শব্দ হতে পারে আবার রিয়াক্ট এর কিছু হতে পারে অথবা যেগুলো এব্রিভিয়েশন সেগুলো ক্ষেত্র বিশেষে ইংরেজি রোমান হরফে রাখা। যেমন, UI, State, ref, escape hatch, DOM, CSS, effect, cache ইত্যাদি। 
- React যেহেতু ব্র্যান্ড নাম। এটা React ই রাখা লাগবে। সেটা ওদের মূল গাইডলাইনে আছে। বিস্তারিত গাইডলাইনের জন্য [এখানে](https://github.com/reactjs/bn.react.dev/issues/32) দেখার অনূরোধ থাকল। 
- ইংরেজিতে কোন কিছু plural এ থাকলেই বাংলাতে সেটা আনা আসলে সব সময় জরুরি বা সুখ পাঠ্য হয় না হুকসময়হের জায়গায় হুক বা হুক্স লেখা যেতে পারে। 

সব মিলিয়ে আপনার অনুবাদ চমৎকার লাগল। এই বিষয়গুলা মাথায় রেখে আরেকটা কমিট দিলে আশা করি মার্জ করা যাবে। তেমন কোন ভুল চোখে পড়ল না। আবারো ধন্যবাদ।

2023-05-24 03:34 UTC, moshfiqrony requested changes
Agreed with @nafistiham bhai. If we can changes those thing we can get the party started for the PR :) Best wish for next page @SusmoySenGupta.

2023-05-24 09:51 UTC, SusmoySenGupta commented
ধন্যবাদ আপনাদের মূল্যবান রিভিউ এর জন্য। আমি টেকনিকাল শব্দ গুলো ইংরেজিতেই রেখে নতুন একটি কমিট দিয়েছি। ধন্যবাদ।

2023-05-28 04:38 UTC, moshfiqrony approved these changes
LGTM

2023-05-28 04:38 UTC, merged