Translate first paragraph of editor setup
reactjs/bn.react.dev pull request #4
Opened 2023-04-30 21:11 UTC by shakib609

2023-05-01 03:47 UTC, ahnafyy commented on src/content/learn/editor-setup.md
> +* কিভাবে আপনার কোড স্বয়ংক্রিয়ভাবেই ফরম্যাট করবেন
স্বয়ংক্রিয়ভাবেই 💯 nicely worded!

2023-05-02 12:06 UTC, moshfiqrony requested changes

2023-05-02 12:06 UTC, moshfiqrony commented on src/content/learn/editor-setup.md
> +আদর্শভাবে, প্রতি সেইভেই আপনার কোডকে আপনার ফরম্যাট করা উচিত। VS Code এ এর সেটিং রয়েছে!
```suggestion
আদর্শভাবে, প্রতি সেইভেই আপনার কোডকে ফরম্যাট করা উচিত। VS Code এ এর জন্য সেটিং রয়েছে!
```

2023-05-02 12:06 UTC, moshfiqrony commented on src/content/learn/editor-setup.md
Assuming this will be translated.

2023-05-02 17:45 UTC, nafistiham commented
LGTM. Merging.

2023-05-02 17:46 UTC, merged

2023-05-02 17:46 UTC, nafistiham reviewed
LGTM