translated: queueing-a-series-of-state-updates
reactjs/bn.react.dev pull request #41
Opened 2023-05-25 12:58 UTC by deveasin

I have translated [queueing-a-series-of-state-updates](https://react.dev/learn/queueing-a-series-of-state-updates) page. If we need any changes, please help me to find it. I will try to solve it. 

Thanks

2023-05-25 15:59 UTC, nafistiham requested changes
স্যান্ডবক্সের কোডের মধ্যে বাংলা আপাতত ঢুকাচ্ছি না আমরা। শুধুমাত্র পেইজের কিছু বাটন আর স্যান্ড বক্সের কমেন্টে বাংলা আনছি।  কারণ কিছু কিছু ক্ষেত্রে স্ক্রিনশটের বিষয় আছে। আর মূল ডকের সাথে মিলার বিষয় আছে। সুতরাং সেটা অনুসারে ভিতরের লেখাও আশা করি ঠিক করে ফেলবেন। দুই-একটা টাইপো ছিল। আরো থাকতে পারে যদি মিস হয়ে থাকে। বাংলা ভাষার সাধারণ ব্যবহারের মত আমরা কোলনের জায়গায় বিসর্গ ব্যবহার করছি। 

অনেক ধন্যবাদ অনেক বড় একটি পেইজের কাজ এগিয়ে ফেলেছেন। @nomandhoni-cs  ভাই, উনার কমিট ফিক্সের পরে আপনি একবার দেখে দিয়েন আমি যদি কিছু মিস করে থাকি।

2023-05-25 15:59 UTC, nafistiham commented on src/components/MDX/Recap.tsx
> +        সারসংক্ষেপ
পুনরালোচনা হওয়া উচিত না?

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +State ভেরিয়েবল সেট করা হলে আরেকটি রেনডারকে সারিবদ্ধ করবে। কিন্তু পরের রেনডারকে সারিবদ্ধ করার আগে, কখনো কখনো আপনি হয়তো ভালুতে অনেকগুলো অপারেশন করতে চাইতে পারেন। এটা করতে, React কিভাবে state আপডেট গুল
```suggestion
State ভেরিয়েবল সেট করা হলে আরেকটি রেন্ডারকে সারিবদ্ধ করবে। কিন্তু পরের রেন্ডারকে সারিবদ্ধ করার আগে, কখনো কখনো আপনি হয়তো ভ্যালুতে অনেকগুলো অপারেশন করতে চাইতে পারেন। এটা করতে, React কিভাবে state আপডেট গুলোকে ব্যাচ করে তা বুঝতে পারবেন।
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +কিন্তু এখানে অন্য একটি ফ্যাক্টর কাজ করে। **React আপনার state আপডেটগুলো প্রচেসসিং করার আগে, ইভেন্ট হ্যান্ডলারের *সকল* কোড রান করা পর্যন্ত অপেক্ষা করে।** এই কারণে সকল `setNumber()` ফাংশন কল করার *পরে*,
```suggestion
কিন্তু এখানে অন্য একটি ফ্যাক্টর কাজ করে। **React আপনার state আপডেটগুলো প্রসেসিং করার আগে, ইভেন্ট হ্যান্ডলারের *সকল* কোড রান করা পর্যন্ত অপেক্ষা করে।** এই কারণে সকল `setNumber()` ফাংশন কল করার *পরে*, শুধুমাত্র তখনি রি-রেন্ডার ঘটে।
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +## পরবর্তী রেন্ডারের আগে একই state একাদিকবার আপডেট করা {/*updating-the-same-state-multiple-times-before-the-next-render*/}
```suggestion
## পরবর্তী রেন্ডারের আগে একই state একাধিকবার আপডেট করা {/*updating-the-same-state-multiple-times-before-the-next-render*/}
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +এখন কাউন্টার বৃদ্ধি করার চেষ্টা করুন:
```suggestion
এখন কাউন্টার বৃদ্ধি করার চেষ্টা করুনঃ
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +চূড়ান্ত ফলাফল হিসাবে react `3` কে সঞ্চয় করে এবং `useState` এ রিটার্ন করে।
```suggestion
চূড়ান্ত ফলাফল হিসাবে react `3` কে স্টোর এবং `useState` এ রিটার্ন করে।
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +      }}>+৩</button>
```suggestion
      }}>+3</button>
```
বাংলা লেখার মধ্যে কোড অনুসারেই রাখা উচিত। এখন আমরা কোডের কমেন্ট ছাড়া কোন কিছুতে হাত দিতে চাচ্ছি  না। বাকিগুলোতে মার্ক করলাম না।

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +      }}>সংখ্যার মান বৃদ্ধি করুন</button>
কোডে পরিবর্তন না করি

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +আপনি যদি আটকে জান তবে এই কোড কাঠামো দিয়ে শুরু করুন:
```suggestion
আপনি যদি আটকে যান তবে এই কোড কাঠামো দিয়ে শুরু করুনঃ
```

2023-05-25 15:59 UTC, nafistiham commented on src/content/learn/queueing-a-series-of-state-updates.md
> +`HandleClick` ইভেন্ট হ্যান্ডলারের ভিতরে, `পেন্ডিং` এবং `সম্পূর্ণ` এর মানগুলি ক্লিক ইভেন্টের সময় যা ছিল তার সাথে মিলে যায়। প্রথম রেন্ডারের জন্য, `পেন্ডিং` ছিল `0`, তাই `setPending(pending - 1)` হয়ে
```suggestion
`HandleClick` ইভেন্ট হ্যান্ডলারের ভিতরে, `পেন্ডিং` এবং `সম্পূর্ণ` এর মানগুলি ক্লিক ইভেন্টের সময় যা ছিল তার সাথে মিলে যায়। প্রথম রেন্ডারের জন্য, `পেন্ডিং` ছিল `0`, তাই `setPending(pending - 1)` হয়ে `setPending(-1)`, যা ভুল। যেহেতু আপনি কাউন্টারগুলিকে *বৃদ্ধি* বা *হ্রাস* করতে চান, ক্লিক করার সময় নির্ধারিত একটি কংক্রিট মান সেট করার পরিবর্তে, আপডেটার ফাংশনগুলি পাস করতে পারেনঃ
```

2023-05-25 19:41 UTC, nafistiham commented
@deveasin , may I know why you are putting every line of change with one commit?

2023-05-25 20:18 UTC, deveasin commented on src/content/learn/queueing-a-series-of-state-updates.md
> +      }}>সংখ্যার মান বৃদ্ধি করুন</button>
Updated thanks

2023-05-25 20:21 UTC, deveasin commented
@nafistiham Sorry, I did it from the github when I was reviewing the comments(I thought it was easier to do it). Next time I will not do it.

---
Thanks a lot for reviewing it. I have updated the requested changes. You may review it again please when you are free.
--

Sorry again for the inconvenience. 


Thanks

2023-05-25 23:03 UTC, nafistiham commented
Oh no it's not an issue. I thought, could you have done it intentionally Haha. Hence asked.

2023-05-26 07:41 UTC, nomandhoni-cs commented
> স্যান্ডবক্সের কোডের মধ্যে বাংলা আপাতত ঢুকাচ্ছি না আমরা। শুধুমাত্র পেইজের কিছু বাটন আর স্যান্ড বক্সের কমেন্টে বাংলা আনছি। কারণ কিছু কিছু ক্ষেত্রে স্ক্রিনশটের বিষয় আছে। আর মূল ডকের সাথে মিলার বিষয় আছে। সুতরাং সেটা অনুসারে ভিতরের লেখাও আশা করি ঠিক করে ফেলবেন। দুই-একটা টাইপো ছিল। আরো থাকতে পারে যদি মিস হয়ে থাকে। বাংলা ভাষার সাধারণ ব্যবহারের মত আমরা কোলনের জায়গায় বিসর্গ ব্যবহার করছি।
> 
> অনেক ধন্যবাদ অনেক বড় একটি পেইজের কাজ এগিয়ে ফেলেছেন। @nomandhoni-cs ভাই, উনার কমিট ফিক্সের পরে আপনি একবার দেখে দিয়েন আমি যদি কিছু মিস করে থাকি।

I apologize for the delay, but I've been working on a Hackathon project. I'll have this done by this evening.

2023-05-26 14:58 UTC, nomandhoni-cs approved these changes

2023-05-26 14:58 UTC, nomandhoni-cs commented on src/content/learn/queueing-a-series-of-state-updates.md
> +ইভেন্ট হ্যান্ডলার সম্পূর্ণ হওয়ার পরে, React পুনরায় একটি রেন্ডার ট্রিগার করবে। পুনরায় রেন্ডার করার সময়, React সারিটি প্রক্রিয়া করবে। আপডেটার ফাংশনগুলি রেন্ডারিংয়ের সময় চলে, তাই **আপডেটার ফাংশনগ
```suggestion
ইভেন্ট হ্যান্ডলার সম্পূর্ণ হওয়ার পরে, React পুনরায় একটি রেন্ডার ট্রিগার করবে। পুনরায় রেন্ডার করার সময়, React সারিটি প্রক্রিয়া করবে। আপডেটার ফাংশনগুলি রেন্ডারিংয়ের সময় চলে, তাই **আপডেটার ফাংশনগুলি অবশ্যই [বিশুদ্ধ](/learn/keeping-components-pure)** হতে হবে এবং ফলাফলটি শুধুমাত্র *রিটার্ন* করতে হবে। তাদের ভিতর থেকে state সেট করার চেষ্টা করবেন না বা অন্যান্য পার্শ্ব প্রতিক্রিয়া চালাবেন না। Strict মোডে, React আপনার ভুল খুঁজে পেতে সাহায্য করার জন্য প্রতিটি আপডেটার ফাংশন দুবার চালাবে (কিন্তু দ্বিতীয় ফলাফলটি বাতিল করবে)।
```

2023-05-27 03:52 UTC, moshfiqrony commented
@deveasin is it completed from your side? I mean all the reviews?

2023-05-27 06:46 UTC, deveasin commented
@moshfiqrony All request changes have been done from my side.

2023-05-27 06:58 UTC, moshfiqrony commented
Great I will try to give my review by tonight.

2023-05-28 04:10 UTC, moshfiqrony approved these changes
LGTM

2023-05-28 04:11 UTC, merged