translated: useEffect hook
reactjs/bn.react.dev pull request #44
Opened 2023-05-27 05:08 UTC by lifeparticle

I have translated a part of the [useEffect](https://bn-react-dev.vercel.app/reference/react/useEffect) hook page.

2023-05-28 04:17 UTC, moshfiqrony commented
Did you asked to translate this page? Or any maintainer assigned you in this page. I can't see that.

2023-05-28 07:09 UTC, lifeparticle commented
@moshfiqrony Thank you for assigning the page. Would you like for me to translate the whole page into one PR?

2023-05-28 07:14 UTC, moshfiqrony commented
If the page is too large we can divide it into multiple PRs. But I think 1 is enough for this page.

2023-05-28 07:17 UTC, lifeparticle commented
Understood, I'll translate the whole page into one PR. Thanks!

2023-06-04 03:19 UTC, moshfiqrony requested changes
Overall the translations are very mechanical. try to be ease with your translations. Like how you would teach it to your friend or your fellow junior.

2023-06-04 03:19 UTC, moshfiqrony commented on src/content/reference/react/useEffect.md
> +একটি ইফেক্ট ডিক্লেয়ার করার জন্য আপনার কম্পোনেন্টের শীর্ষ স্তরে `useEffect` কল করুন:
Translation ta joto ta bujhte valo lage oivabe korar chesta korun. `শীর্ষ স্তরে` ekti suddho bangla. Normali puro translation e cholito bangla bebohar kora hoy. tai eitike apni onnovabe likhte parten
```suggestion
একটি ইফেক্ট ডিক্লেয়ার করার জন্য আপনার কম্পোনেন্টের একদম উপরে `useEffect` কল করুন:
```

2023-06-04 03:19 UTC, moshfiqrony commented on src/content/reference/react/useEffect.md
> +* `setup`: আপনার ইফেক্টের যুক্তি সহ ফাংশন। আপনার সেটআপ ফাংশন অপশনালি একটি *cleanup* ফাংশন রিটার্ন করতে পারে। যখন আপনার কম্পোনেন্টটি DOM-এ যুক্ত করা হয়, React আপনার সেটআপ ফাংশন চালাবে। প্রতিটি রি-রেন
Reading ta ektu mechanical. Normally amra jeivabe kothaboli emon na. Apnar jodi mone hoy je puro banglay oivabe likha jacchena kichu english use koren. Kintu porte jeno moja lage. If needed someone else will take another stab on it later if they comeup with a new good bangla of that line.

2023-07-30 03:47 UTC, moshfiqrony commented
Any update on this?

2023-08-02 12:33 UTC, lifeparticle commented
Hello, sorry for the late reply; I'll try to finish it by this month; thanks for your patience.

2025-02-20 02:46 UTC, closed without merging