First commit, minor changes
reactjs/bn.react.dev pull request #46
Opened 2023-05-29 20:38 UTC by shm-dsgn

2023-05-30 05:17 UTC, shm-dsgn commented
Can any maintainer help me out a bit by reviewing what I have done so far so that I can know how to proceed/if i have translated it properly and should proceed in the same way?

Thank you

2023-06-03 09:01 UTC, nafistiham requested changes
কোন একটা জায়গায় লাইন মিলেনি +39 -38 দেখাচ্ছে। আমরা চেষ্টা করছি ইংরেজির সাথে হুবহু লাইন মিলিয়ে অনুবাদ করার। কিছু টেকনিকাল শব্ধ এবং কোডে ব্যবহৃত বাটনের নাম, রিয়াকশন এগুলো ইংরেজিতে বা অন্তত ইংরেজি উচ্চারণে রাখা শ্রেয়। দ্বিমত থাকলে অবশ্যই জানাবেন। আগাম ধন্যবাদ।

2023-06-03 09:53 UTC, shm-dsgn commented on src/content/learn/reacting-to-input-with-state.md
> +* কিভাবে ঘোষণামূলক UI প্রোগ্রামিং অপরিহার্য UI প্রোগ্রামিং থেকে আলাদা
So should I change Imperative as well?

2023-06-03 10:10 UTC, nafistiham commented on src/content/learn/reacting-to-input-with-state.md
> +* কিভাবে ঘোষণামূলক UI প্রোগ্রামিং অপরিহার্য UI প্রোগ্রামিং থেকে আলাদা
Yes. Missed it.

2023-06-03 16:48 UTC, shm-dsgn commented
Done with the requested changes

2023-06-03 17:11 UTC, nafistiham requested changes
২৮, ১২৩৫ নম্বর লাইনে একটু চেক করতে হবে। সামান্য গরমিল আছে।

2023-06-03 17:11 UTC, nafistiham commented on src/content/learn/reacting-to-input-with-state.md
> +
```suggestion
```

2023-06-03 17:11 UTC, nafistiham commented on src/content/learn/reacting-to-input-with-state.md
> +</Challenges>
```suggestion

</Challenges>
```

2023-06-04 05:04 UTC, nafistiham approved these changes
LGTM! Thanks a lot!

2023-06-04 05:05 UTC, merged