React components profiler
reactjs/bn.react.dev pull request #59
Opened 2023-06-14 08:36 UTC by nafistiham

2023-06-15 09:11 UTC, aleena314 requested changes

2023-06-15 09:11 UTC, aleena314 commented on src/content/reference/react/Profiler.md
> +
লাইনের অমিল আছে।

2023-06-15 09:11 UTC, aleena314 commented on src/content/reference/react/Profiler.md
> +যদি `<Profiler>` একটা হালকা কম্পোনেন্ট, এটা শুধুমাত্র তখনি ব্যবহার করা উচিত যখন প্রয়োজন পড়ছে। প্রতি বার ব্যবহারে অ্যাপের CPU এবং Memory এর উপরে অতিরিক্ত কিছু চাপ পড়ে।
যদিও হবে।

2023-06-17 11:45 UTC, moshfiqrony approved these changes
LGTM

2023-06-17 11:46 UTC, merged