Describing the UI
reactjs/bn.react.dev pull request #62
Opened 2023-06-19 15:48 UTC by nafistiham

2023-06-20 05:55 UTC, aleena314 requested changes

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +React একটা জাভাস্ক্রিপ্ট লাইব্রেরি যার কাজ user interfaces (UI) রেন্ডার করা। UI বিচিন্ন ক্ষুদ্র একক যেমন বাটন, টেক্সট বা ছবির মাধ্যমে গোড়ে ওঠে। React আপনাকে সুযোগ দেয় সেগুলোকে reusable, nestable *কম্
বিচিন্ন > বিভিন্ন
গোড়ে > গড়ে
ওয়েবসাইট থেকে ফোনের অ্যাপ > ওয়েবসাইট হোক বা ফোনের অ্যাপ

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +## JSX দিয়া মার্ক আপ লেখা {/*writing-markup-with-jsx*/}
মার্কাপ ?
মার্কআপ ?

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +JSX আপনাকে একটা জাভাস্ক্রিপ্ট ফাইলে HTML এর মত মার্কআপ লিখতে দেয়, এতে রেন্ডারিং লজিক আর কনটেন্ট একি জায়গায় থাকে। মাঝে মাঝে আপনি চাইবেন সেই মার্কআপের মধ্যে কিছু জাভাস্ক্রিপ্ট লজিক যুক্ত করতে বা ডাইনাম
জানা > জানালা

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +React কম্পোনেন্ট নিজেদের মধ্যে যোগাযোগ করতে *প্রপ* ব্যবহার করে। যেকোন প্যারেন্ট কম্পোনেন্ট তার চাইল্ড কম্পোনেন্টে তথ্য পাঠাতে পারে প্রপ দেবার মাধ্যমে। প্রপ হয়ত আপনাকে HTML এট্রিবিউটের কথা মনে করিয়ে দ
পারেম > পারেন

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +কীভাবে pure এবং অনুমানযোগ্য ফাংশন হিসেবে কম্পোনেন্ট লিখবেন জানতে পড়ুন **[কম্পোনেন্ট pure রাখা।]
** বাদ গেছে

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +* **একই ইনপুটের একই আউটপুট/** একই ইনপুট দেওয়া হলে একটা pure ফাংশন সব সময় একই আউটপুটই দেয়।
/ > ।

2023-06-20 05:55 UTC, aleena314 commented on src/content/learn/describing-the-ui.md
> +কীভাবে একটা কম্পোনেন্টের লিস্ট রেন্ডার করবেন এবং কীভাবে একটা key নির্দিষ্ট করবেন জানতে পড়ুন **[লিস্টের রেন্ডারিং](/learn/rendering-lists)** to learn how to render a list of components, and how to cho
ইংরেজি রয়ে গেছে।

2023-06-20 06:01 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +React একটা জাভাস্ক্রিপ্ট লাইব্রেরি যার কাজ user interfaces (UI) রেন্ডার করা। UI বিচিন্ন ক্ষুদ্র একক যেমন বাটন, টেক্সট বা ছবির মাধ্যমে গোড়ে ওঠে। React আপনাকে সুযোগ দেয় সেগুলোকে reusable, nestable *কম্
fixed

2023-06-20 06:01 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +React অ্যাপ্লিকেশনগুলো UI এর পৃথক পৃথক কিছু অংশের মাধ্যমে গড়ে ওঠে যাদের নাম *কম্পোনেন্ট*। একটা React কম্পোনেন্ট হচ্ছে একটা জাভাস্ক্রিপ্ট ফাংশন যা আপনি মার্কাপ দিয়ে সুন্দর করে তুলতে পারেন। একটা কম্পোন
all are now মার্কাপ

2023-06-20 06:01 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +JSX আপনাকে একটা জাভাস্ক্রিপ্ট ফাইলে HTML এর মত মার্কআপ লিখতে দেয়, এতে রেন্ডারিং লজিক আর কনটেন্ট একি জায়গায় থাকে। মাঝে মাঝে আপনি চাইবেন সেই মার্কআপের মধ্যে কিছু জাভাস্ক্রিপ্ট লজিক যুক্ত করতে বা ডাইনাম
done

2023-06-20 06:01 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +React কম্পোনেন্ট নিজেদের মধ্যে যোগাযোগ করতে *প্রপ* ব্যবহার করে। যেকোন প্যারেন্ট কম্পোনেন্ট তার চাইল্ড কম্পোনেন্টে তথ্য পাঠাতে পারে প্রপ দেবার মাধ্যমে। প্রপ হয়ত আপনাকে HTML এট্রিবিউটের কথা মনে করিয়ে দ
fixed

2023-06-20 06:02 UTC, moshfiqrony requested changes

2023-06-20 06:02 UTC, moshfiqrony commented on src/content/learn/describing-the-ui.md
> +* [JSX দিয়ে কীভাবে জাভাস্ক্রিপ্টে marrkap যুক্ত করবেন](/learn/writing-markup-with-jsx)
```suggestion
* [JSX দিয়ে কীভাবে জাভাস্ক্রিপ্টে markup যুক্ত করবেন](/learn/writing-markup-with-jsx)
```

2023-06-20 06:04 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +কীভাবে pure এবং অনুমানযোগ্য ফাংশন হিসেবে কম্পোনেন্ট লিখবেন জানতে পড়ুন **[কম্পোনেন্ট pure রাখা।]
done

2023-06-20 06:04 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +* **একই ইনপুটের একই আউটপুট/** একই ইনপুট দেওয়া হলে একটা pure ফাংশন সব সময় একই আউটপুটই দেয়।
done

2023-06-20 06:04 UTC, nafistiham commented on src/content/learn/describing-the-ui.md
> +কীভাবে একটা কম্পোনেন্টের লিস্ট রেন্ডার করবেন এবং কীভাবে একটা key নির্দিষ্ট করবেন জানতে পড়ুন **[লিস্টের রেন্ডারিং](/learn/rendering-lists)** to learn how to render a list of components, and how to cho
fixed

2023-06-21 06:48 UTC, moshfiqrony approved these changes
LGTM

2023-06-21 06:49 UTC, merged