Use insertion effect
reactjs/bn.react.dev pull request #77
Opened 2023-08-03 06:27 UTC by nafistiham

2023-08-06 03:54 UTC, nomandhoni-cs requested changes
@nafistiham Bhai, I was little bit busy.
That's why review korte ektu late hoise.
Anyway thanks a lot for this long page.

2023-08-06 03:54 UTC, nomandhoni-cs commented on src/content/reference/react/useInsertionEffect.md
> +* **optional** `dependencies`: `setup` কোডের মধ্যে রেফারেন্স করা সকল রিয়াক্টিভ ভ্যালুর তালিকা। রিয়াক্টিভ ভ্যালুর মধ্যে রয়েছে props, state এবং আপনার কম্পোনেন্ট বডির মধ্যে সরাসরি ডিক্লেয়ার হঅ্যা সকল ভ্
```suggestion
* **optional** `dependencies`: `setup` কোডের মধ্যে রেফারেন্স করা সকল রিয়াক্টিভ ভ্যালুর তালিকা। রিয়াক্টিভ ভ্যালুর মধ্যে রয়েছে props, state এবং আপনার কম্পোনেন্ট বডির মধ্যে সরাসরি ডিক্লেয়ার হওয়া সকল ভ্যারিয়েবল এবং ফাংশন। যদি আপনার লিন্টার  [React এর জন্য কনফিগার করা থাকে](/learn/editor-setup#linting), এটা নিশ্চিত করবে যে প্রতিটা রিয়াক্টিভ ভ্যালু সঠিকভাবে ডিপেন্ডেন্সি হিসেবে চিহ্নিত করা আছে। ডিপেন্ডেন্সির তালিকাতে অবশ্যই আইটেমের সংখ্যা ধ্রুবক হতে হবে এবং `[dep1, dep2, dep3]` এর মত ইনলাইনে থাকতে হবে।  React will compare each dependency with its previous value using the [`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison algorithn ব্যবহার করে প্রতিটা ডিপেন্ডেন্সি এবং এর আগের ভ্যালু তুলনা করবে।আপনি যদি ডিপেন্ডেন্সি চিহ্নিত করে না দেন, আপনার Effect কম্পোনেন্টের প্রতিটি re-render এ re-run হবে।
```

2023-08-06 03:54 UTC, nomandhoni-cs commented on src/content/reference/react/useInsertionEffect.md
> +কেউ কেউ CSS ফাইল লেখবার জায়গায় সরাসরি জাভস্ক্রিপ্ট এর মধ্যে স্টাইল অথর করা পছন্দ করেন। এতে সাধারণত কোন CSS-in-JS লাইব্রেরি বা কোন একটি টুল ব্যবহার করা প্রয়োজন পড়ে। CSS-in-JS ব্যবহারের তিনটি বহুল ব্যব
```suggestion
কেউ কেউ আলাদা CSS ফাইলে স্টাইল করার কোড লেখার চেয়ে জাভাস্ক্রিপ্টে স্টাইল কোড লিখতে পছন্দ করেন। এতে সাধারণত কোন CSS-in-JS লাইব্রেরি বা কোন একটি টুল ব্যবহার করা প্রয়োজন পড়ে। CSS-in-JS ব্যবহারের তিনটি বহুল ব্যবহৃত পদ্ধতি আছেঃ
```

2023-08-06 03:54 UTC, nomandhoni-cs commented on src/content/reference/react/useInsertionEffect.md
> +`useEffect` এর ন্যায়, `useInsertionEffect` সার্ভারে রান করে না। আপনার যদু সার্ভারে ব্যবহৃত CSS rule গুলো সংগ্রহ করার প্রয়োজন পড়ে, আপনি সেটা রেন্ডারিং এর সময়ে করতে পারেনঃ
```suggestion
`useEffect` এর ন্যায়, `useInsertionEffect` সার্ভারে রান করে না। আপনার যদি সার্ভারে ব্যবহৃত CSS rule গুলো সংগ্রহ করার প্রয়োজন পড়ে, আপনি সেটা রেন্ডারিং এর সময়ে করতে পারেনঃ
```

2023-08-08 05:40 UTC, nafistiham commented on src/content/reference/react/useInsertionEffect.md
> +কেউ কেউ CSS ফাইল লেখবার জায়গায় সরাসরি জাভস্ক্রিপ্ট এর মধ্যে স্টাইল অথর করা পছন্দ করেন। এতে সাধারণত কোন CSS-in-JS লাইব্রেরি বা কোন একটি টুল ব্যবহার করা প্রয়োজন পড়ে। CSS-in-JS ব্যবহারের তিনটি বহুল ব্যব
done

2023-08-08 05:41 UTC, nafistiham commented on src/content/reference/react/useInsertionEffect.md
> +`useEffect` এর ন্যায়, `useInsertionEffect` সার্ভারে রান করে না। আপনার যদু সার্ভারে ব্যবহৃত CSS rule গুলো সংগ্রহ করার প্রয়োজন পড়ে, আপনি সেটা রেন্ডারিং এর সময়ে করতে পারেনঃ
done

2023-08-08 05:50 UTC, nafistiham commented
@nomandhoni-cs change request resolved. Merge when possible.

2023-08-08 06:40 UTC, merged