Passing data deeply with context (5%)
reactjs/bn.react.dev pull request #92
Opened 2023-09-23 15:10 UTC by HabibMollah

2023-09-23 15:13 UTC, HabibMollah commented
আপাতত কাজ শেষ।

2023-09-24 16:51 UTC, HabibMollah commented
এতটুকুর কেউ রিভিউ দিয়ে দিন

2023-09-25 07:10 UTC, moshfiqrony reviewed
Looks good to me. Great start

2023-09-26 11:38 UTC, HabibMollah commented
এতটুক ঠিকাছে তো?

2023-10-24 07:01 UTC, HabibMollah commented
এই পেজ তাহলে এখানে শেষ করছি।

2023-10-26 06:19 UTC, nafistiham requested changes
বেশ সুন্দর অনুবাদ হয়েছে। অনেক ধন্যবাদ বড় একটি কাজ শেষ করবার জন্য। কিছু চেইঞ্জ রিকুয়েস্ট দেওয়া অ্যাছে। দ্বিমত থাকলে জানাবেন। keep contributing!

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +সাধারণত, আপনি props এর মাধ্যমে একটি প্যারেন্ট কম্পোনেন্ট থেকে একটি চাইল্ড কম্পোনেন্টে ইনফর্মেশন pass করবেন। কিন্তু যদি আপনার props কে মাঝের অনেক অনেক কম্পোনেন্টের মধ্যে দিয়ে pass করা লাগে, অথবা আপনা
যদি সহজ বাংলা থাকে তাহলে তৎসম শব্দের ব্যবহার না করি।
```suggestion
সাধারণত, আপনি props এর মাধ্যমে একটি প্যারেন্ট কম্পোনেন্ট থেকে একটি চাইল্ড কম্পোনেন্টে ইনফর্মেশন pass করবেন। কিন্তু যদি আপনার props কে মাঝের অনেক অনেক কম্পোনেন্টের মধ্যে দিয়ে pass করা লাগে, অথবা আপনার অ্যাপের অনেক কম্পোনেন্টের একই ইনফর্মেশনের দরকার হয়, তখন props পাস করা শব্দবহুল এবং ঝামেলাপূর্ণ হতে পারে। *Context* প্যারেন্ট কম্পোনেন্টকে এর নিচের যেকোনো স্তরের যেকোনো কম্পোনেন্টের জন্য কিছু ইনফর্মেশন অ্যাভেইলেবল করতে দেয় (সে নিচের কম্পোনেন্ট যতই গভীরে হোক না কেনো) এ ইনফর্মেশনকে props এর মাধ্যমে স্পষ্টভাবে pass করাও লাগেনা।
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +এমন হলে কী চমৎকার হতোনা যদি প্রপস পাস না করেই tree এর মধ্যে যে কম্পোনেন্টগুলোর ডেটাটি প্রয়োজন সেগুলোর কাছে ডেটাকে "ম্যাজিকের মতো" নিয়ে যাওয়ার কোন উপায় থাকতো? React এর context ফিচারই হলো সে উপায়!
```suggestion
এমন হলে কী চমৎকার হতো না যদি প্রপস পাস না করেই tree এর মধ্যে যে কম্পোনেন্টগুলোর যে ডেটা প্রয়োজন সেগুলোর কাছে সেই ডেটা "ম্যাজিকের মতো" নিয়ে যাওয়ার কোন উপায় থাকত? React এর context ফিচারই হলো সে উপায়!
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +কনটেক্সট একটি প্যারেন্ট কম্পোনেন্টকে এর নিম্নস্থ সকল কম্পনেন্টের tree কে ডেটা সরবরাহ করতে দেয়। কনটেক্সটের বহু ব্যবহার রয়েছে। একটি উদাহরণ দেখা যাক। এই `Heading` কম্পোনেন্টকে একটু দেখুন যেটি এর সাইজে
কিছু জায়গায় কম্পনেন্ট থাকতে পারে। একবার ফাইন্ড করে রিপ্লেস করে নিবেন। 
```suggestion
কনটেক্সট একটি প্যারেন্ট কম্পোনেন্টকে এর নিম্নস্থ সকল কম্পোনেন্টের tree কে ডেটা সরবরাহ করতে দেয়। কনটেক্সটের বহু ব্যবহার রয়েছে। একটি উদাহরণ দেখা যাক। এই `Heading` কম্পোনেন্টকে একটু দেখুন যেটি এর সাইজের জন্য কোনো `level` গ্রহণ করে:
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +কিন্তু `<Heading>` কম্পোনেন্টটি কিভাবে এর সবচেয়ে কাছের `<Section>` এর level জানবে? **তা করার জন্য tree এর উপরের কোথাও বিদ্যমান ডাটা, চাইল্ডের "তালাশ করার" জন্য কোনো উপায় থাকা লাগবে।**
```suggestion
কিন্তু `<Heading>` কম্পোনেন্টটি কিভাবে এর সবচেয়ে কাছের `<Section>` এর level জানবে? **তা করার জন্য tree এর উপরের কোথাও বিদ্যমান ডাটা, চাইল্ডের "চাইবার" জন্য কোনো উপায় থাকা লাগবে।**
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +এটা রিয়েক্টকে বলে দেয় যে: "যদি এই `<Section>` এর ভিতরের কোনো কম্পোনেন্ট `LevelContext` তালাশ করে, তবে তাকে এই `level` দিয়ে দাও"। তখন কম্পোনেন্টটি UI ট্রি এর ভিতর এর সবচেয়ে কাছের `<LevelContext.Pr
যদি অন্য কোথাও থাকে, ঠিক করে নিবেন। আমরা পুরো প্রজেক্ট জুড়ে React লিখার সিদ্ধান্ত নিয়েছি।
```suggestion
এটা React কে বলে দেয় যে: "যদি এই `<Section>` এর ভিতরের কোনো কম্পোনেন্ট `LevelContext` তালাশ করে, তবে তাকে এই `level` দিয়ে দাও"। তখন কম্পোনেন্টটি UI ট্রি এর ভিতর এর সবচেয়ে কাছের `<LevelContext.Provider>` এর ভ্যালু ইউজ করবে।
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +এই পরিবর্তনের করে, আপনার `level` প্রপটিকে `<Section>` কিংবা `<Heading>` *কোনোটিকেই* পাস করা লাগবে না:
```suggestion
এই পরিবর্তনের কারণে, আপনার `level` প্রপটিকে `<Section>` কিংবা `<Heading>` *কোনোটিকেই* পাস করা লাগবে না:
```

2023-10-26 06:19 UTC, nafistiham commented on src/content/learn/passing-data-deeply-with-context.md
> +এই এক্সাম্পলটি হেডিং লেভেলের ব্যবহার করেছে কারণ এতে দেখা যায় যে নেস্টেড কম্পোনেন্ট কিভাবে কনটেক্সটের ভ্যালু পুনরায় পরিবর্তন করে দিতে পরে। কিন্তু কনটেক্সট আরো অনেক ক্ষেত্রেও কাজে আসে। অ্যাপের নিম্নস
```suggestion
এই উদাহরণটি হেডিং লেভেলের ব্যবহার করেছে কারণ এতে দেখা যায় যে নেস্টেড কম্পোনেন্ট কিভাবে কনটেক্সটের ভ্যালু পুনরায় পরিবর্তন করে দিতে পরে। কিন্তু কনটেক্সট আরো অনেক ক্ষেত্রেও কাজে আসে। অ্যাপের নিম্নস্থ subtree এর প্রয়োজন এমন যেকোনো ইনফর্মেশন আপনি নিচের দিকে পাস করে দিতে পারেন: বর্তমান কালার থিম, বর্তমানে যে ইউজার লগড ইন ইত্যাদি।
```

2023-10-26 13:24 UTC, HabibMollah commented on src/content/learn/passing-data-deeply-with-context.md
> +এমন হলে কী চমৎকার হতোনা যদি প্রপস পাস না করেই tree এর মধ্যে যে কম্পোনেন্টগুলোর ডেটাটি প্রয়োজন সেগুলোর কাছে ডেটাকে "ম্যাজিকের মতো" নিয়ে যাওয়ার কোন উপায় থাকতো? React এর context ফিচারই হলো সে উপায়!
হুম, এটা নিয়ে আমিও দ্বিধার মধ্যে ছিলাম কোন শব্দটা ব্যবহার করলে সুন্দর শোনায়। তবে কোনো সন্দেহ নেই যে "নিচের" শব্দটি বেশি সহজবোধ্য।

2023-10-26 13:29 UTC, HabibMollah commented on src/content/learn/passing-data-deeply-with-context.md
> +কনটেক্সট একটি প্যারেন্ট কম্পোনেন্টকে এর নিম্নস্থ সকল কম্পনেন্টের tree কে ডেটা সরবরাহ করতে দেয়। কনটেক্সটের বহু ব্যবহার রয়েছে। একটি উদাহরণ দেখা যাক। এই `Heading` কম্পোনেন্টকে একটু দেখুন যেটি এর সাইজে
এই টাইপোটা কীভাবে চোখ এড়িয়ে গেলো বুঝলাম না। অসংখ্য ধন্যবাদ। সব চেক করে আর পাইনি।

2023-10-26 13:31 UTC, HabibMollah commented on src/content/learn/passing-data-deeply-with-context.md
> +এটা রিয়েক্টকে বলে দেয় যে: "যদি এই `<Section>` এর ভিতরের কোনো কম্পোনেন্ট `LevelContext` তালাশ করে, তবে তাকে এই `level` দিয়ে দাও"। তখন কম্পোনেন্টটি UI ট্রি এর ভিতর এর সবচেয়ে কাছের `<LevelContext.Pr
ঠিকাছে ভাই

2023-10-26 13:39 UTC, HabibMollah commented
@nafistiham অসংখ্য ধন্যবাদ ভাই।

2023-10-26 14:28 UTC, HabibMollah commented
আপাতত সব ফিক্স করে দিয়েছি

2023-10-29 04:06 UTC, moshfiqrony approved these changes
Really great translation. Great work @HabibMollah :heart:

2023-10-29 05:44 UTC, nafistiham approved these changes
LGTM

2023-10-29 05:44 UTC, merged