feat: translate intro of scaling up with reducer and context page
reactjs/bn.react.dev pull request #93
Opened 2023-09-24 02:46 UTC by Shahriar-Rumel

2023-09-24 03:34 UTC, moshfiqrony approved these changes
LGTM

2023-10-20 04:26 UTC, Shahriar-Rumel commented
@moshfiqrony I am done with the translation of this page, please review the changes.
Thanks.

2023-10-20 05:11 UTC, nafistiham requested changes
অনেক ধন্যবাদ বড় একটি পেইজে স্বেচ্ছাসেবা দেবার জন্য।
কিছু পরিবর্তনের অনুরোধ থাকবে।
১। খুব অপরিচিত তৎসম শব্দের ব্যবহারের প্রয়োজন নেই। অর্থ বুঝা যায় এমন করে ভাবানুবাদ যথেষ্ট।
২। টেকনিকাল শব্দ ইংরেজি উচ্চারণে বা সরাসরি ইংরেজিতে রাখতে হবে।
৩। কিছু লাইন উপর নিচ হয়েছে। যেই লাইনে ইংরেজি একই লাইনে বাংলা লিখতে হবে। লাইন কমানো বা বাড়ানো যাবে না।
৪। অনেক ক্ষেত্রে ণ এর জায়গায় ন এর ব্যবহার খেয়াল করেছি। কিছু জায়গা ঠিক করে দিয়েছি। আরো থাকতে পারে। 
৫। দাড়ি এবং কমার আগে স্পেইস হবে না, তবে পরে হবে। 

আবারো ধন্যবাদ।

2023-10-20 05:11 UTC, nafistiham commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +[Reducers এর সাথে পরিচিতি](/learn/extracting-state-logic-into-a-reducer) এই উদাহরণে, state কে reducer ব্যবস্থাপনা করেছে । Reducer ফাংশনটি সকল state হালানাগাদ যুক্তিসমূহ ধারন করে এবং একে ফাইলের একদম শ
```suggestion
[Reducers এর সাথে পরিচিতি](/learn/extracting-state-logic-into-a-reducer) এর এই উদাহরণে, state কে reducer ব্যবস্থাপনা করেছে। Reducer ফাংশনটি সকল state আপডেট যুক্তিসমূহ ধারণ করে এবং একে ফাইলের একদম শেষে ডিক্লেয়ার করা হয়।
```

অনেক ইংরেজি শব্দ যেগুলো তার আভিধানিক বাংলার চেয়ে বেশি ব্যবহৃত, সেগুলো বাংলা উচ্চারণে লিখে ব্যবহার করাই সুখ পাঠ্য হবে।

2023-10-20 05:11 UTC, nafistiham commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +একটি Reducer ইভেন্ট হ্যান্ডলারগুলি ছোট এবং সংক্ষিপ্ত রাখতে সাহায্য করে । তবে, আপনার অ্যাপ্লিকেশন বাড়তে শুরু করলে, আপনি আরও একটি সমস্যায় পরে যেতে পারেন । **বর্তমানে, `tasks` state এবং `dispatch` ফাং
```suggestion
একটি Reducer ইভেন্ট হ্যান্ডলারগুলি ছোট এবং সংক্ষিপ্ত রাখতে সাহায্য করে । তবে, আপনার অ্যাপ্লিকেশন বড় হতে শুরু করলে, আপনি আরও একটি সমস্যায় পড়ে যেতে পারেন । **বর্তমানে, `tasks` state এবং `dispatch` ফাংশনটি শুধুমাত্র শীর্ষ-স্তরের `TaskApp` কম্পোনেন্টে পাওয়া যাচ্ছে।** অন্য কম্পোনেন্টগুলিকে টাস্কের তালিকা পড়তে অথবা তা পরিবর্তন করতে দিতে হলে, আপনাকে বর্তমান state এবং তা পরিবর্তন করার ইভেন্ট হ্যান্ডলারগুলি explicit ভাবে props হিসেবে [পাঠাতে](/learn/passing-props-to-a-component) হবে।
```

যেসব শব্দ টেকনিকাল অর্থ বহন করে, সেগুলো ইংরেজিতে বা অন্তত ইংরেজি উচ্চারণে রাখতে হবে।

2023-10-20 05:11 UTC, nafistiham commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +একটি ছোট উদাহরনে এটি ভালো কাজ করে, কিন্তু যদি এর মাঝে আপনার দশ বা শতাধিক কম্পোনেন্ট থাকে, তাহলে সকল state এবং ফাংশনগুলিকে পাঠানো অনেক বিরক্তিকর হতে পারে ।
```suggestion
একটি ছোট উদাহরণে এটি ভালো কাজ করে, কিন্তু যদি এর মাঝে আপনার দশ বা শতাধিক কম্পোনেন্ট থাকে, তাহলে সকল state এবং ফাংশনকে পাঠানো অনেক বিরক্তিকর হতে পারে ।
```

2023-10-20 05:11 UTC, nafistiham commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +এই কারনে, props এর মাধমে পাঠানোর বিকল্প হিসেবে, আপনি সমস্ত `tasks` স্টেট এবং  `dispatch` ফাংশনকে [context এর মধ্যে](/learn/passing-data-deeply-with-context) রাখতে পারেন । **এইভাবে, `TaskApp` এর নীচে
```suggestion
এই কারণে, props এর মাধমে পাঠানোর বিকল্প হিসেবে, আপনি সমস্ত `tasks` স্টেট এবং  `dispatch` ফাংশনকে [context এর মধ্যে](/learn/passing-data-deeply-with-context) রাখতে পারেন । **এইভাবে, `TaskApp` এর নীচে যেকোনো কম্পোনেন্ট রুটে আপনি "prop drilling" এর পুনরাবৃত্তি ছাড়াই task পড়তে এবং একশনগুলিকে dispatch করতে পারবেন ।**
```

2023-10-20 05:11 UTC, nafistiham commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +
অতিরিক্ত লাইন। আমরা চেষ্টা করব লাইনে লাইনে মিলাতে।
```suggestion
```

2023-10-20 06:49 UTC, moshfiqrony commented
Thank you so much @Shahriar-Rumel . I will check it at evening

2023-10-20 15:40 UTC, Shahriar-Rumel commented
> অনেক ধন্যবাদ বড় একটি পেইজে স্বেচ্ছাসেবা দেবার জন্য। কিছু পরিবর্তনের অনুরোধ থাকবে। ১। খুব অপরিচিত তৎসম শব্দের ব্যবহারের প্রয়োজন নেই। অর্থ বুঝা যায় এমন করে ভাবানুবাদ যথেষ্ট। ২। টেকনিকাল শব্দ ইংরেজি উচ্চারণে বা সরাসরি ইংরেজিতে রাখতে হবে। ৩। কিছু লাইন উপর নিচ হয়েছে। যেই লাইনে ইংরেজি একই লাইনে বাংলা লিখতে হবে। লাইন কমানো বা বাড়ানো যাবে না। ৪। অনেক ক্ষেত্রে ণ এর জায়গায় ন এর ব্যবহার খেয়াল করেছি। কিছু জায়গা ঠিক করে দিয়েছি। আরো থাকতে পারে। ৫। দাড়ি এবং কমার আগে স্পেইস হবে না, তবে পরে হবে।
> 
> আবারো ধন্যবাদ।

Thanks for your detailed review, I will fix the issues and let you know.

2023-10-21 07:20 UTC, Shahriar-Rumel commented
Hi @nafistiham,
I've made the required changes, please let me know if there's anything else.
Thanks

2023-10-21 07:24 UTC, nafistiham approved these changes
LGTM

2023-10-21 07:24 UTC, merged